version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy 
        required: true
    environment:
        - DATABASE_CONTAINER_NAME=database
        - DATABASE_PORT=5432
        - DATABASE_NAME=infopanel   
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 80:80

  database:
    container_name: database
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=infopanel
    ports:
      - '5432:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - infopanel-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d infopanel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    network_mode: "host"
    environment:
      - MINIO_ACCESS_KEY=minio1234567890
      - MINIO_SECRET_KEY=minio1234567890
    volumes:
      - ./storage:/data
    command: server --console-address ":9001" /data


networks:
  infopanel-network:
    name: infopanel-network

volumes:
 infopanel-db-data:
    name: infopanel-db-data
